version: 0.2
<<<<<<< HEAD
artifacts:
 files:
   - '**/*'  # Include all files and subdirectories
 base-directory: .  # Root directory where files are collected
 discard-paths: no  # Retain original file paths

