version: 0.2

phases:
  build:
    commands:
      # Move the HTML content to the Apache web root
      - echo "Deploying website to Apache"
      - echo "Welcome to my CodeBuild deployed website!" > ./index.html
artifacts:
  files:
    - ./index.html
