version: 0.2
phases:
  install:
    commands:
      # Update the package list
      - echo Installing httpd...
      - sudo yum update -y  # For Amazon Linux / CentOS / RHEL
      - sudo yum install -y httpd

  pre_build:
    commands:
      - echo Starting HTTPD server...
      - sudo service httpd start

  build:
    commands:
      - echo Verifying httpd installation...
      - sudo service httpd status

  post_build:
    commands:
      - echo httpd installation complete.
      - echo HTTPD service running: $(sudo service httpd status)
      - sudo systemctl enable httpd    # Ensure httpd starts on reboot
artifacts:
 files:
   - '**/*'  # Include all files and subdirectories
 
 discard-paths: no  # Retain original file paths

