---
version: 0.2
phases:
  install:
    commands:
      - echo Installing httpd...
      - sudo yum update -y
      - sudo yum install -y httpd
  pre_build:
    commands:
      - echo Starting HTTPD server...
      - sudo service httpd start
  build:
    commands:
      - echo Verifying httpd installation...
      - sudo service httpd status
  post_build:
    commands:
      - echo httpd installation complete.
      - echo HTTPD service running: $(sudo service httpd status)
      - sudo systemctl enable httpd
  artifacts: null
  files:
    - "**/*"
  discard-paths: no


