version: 0.2

phases:
  install:
    commands:
      - echo Installing Apache HTTP Server...
      - sudo yum update -y
      - sudo yum install -y httpd php  # Ensure PHP is also installed
      - sudo service httpd start
      - echo HTTPD started successfully
      - sudo service httpd status  # Check if the service is running

  pre_build:
    commands:
      - echo Starting HTTPD server...
      - echo Verifying HTTPD installation...
      - sudo service httpd status

  build:
    commands:
      - echo Build starting on 'date'
      - sudo mkdir -p /var/www/html
      - cp *.html *.php /var/www/html/
      - echo "Build completed and files copied."

  post_build:
    commands:
      - echo Configuring HTTPD...
      - sudo service httpd restart
      - sudo systemctl enable httpd
      - sudo service httpd status  # Confirm the server is running post-restart

artifacts: {}  # Explicitly defining artifacts as an empty map

files:
  - "**/*"

discard-paths: no
