version: 0.2
phases:
  install:
    commands:
      - echo Installing httpd...
      - sudo yum update -y
      - sudo yum install httpd -y

  pre_build:
    commands:
      - echo starting httpd service..
      - cd /usr/sbin/
      - ./httpd -k start

  build:
    commands:
      - echo Building the application...
      - sudo mkdir -p /var/www/html/
      - sudo cp *.html /var/www/html/
      - echo application file copied successfully

  post_build:
    commands:
      - echo Build completed.
      - ls -l
artifacts:
 files:
  - "**/*"
 discard-paths: no
