---
version: 0.2
phases:
  install:
    commands:
      - echo Installing Apache HTTP Server...
      - sudo yum update -y
      - sudo yum install -y httpd
      - sudo service httpd start
      - echo httpd started successfully
  pre_build:
    commands:
      - echo Starting HTTPD server...
      - echo Verifying HTTPD installation...
      - sudo service httpd status
  build:
    commands:
      - echo buils starting on 'date'
      - sudo mkdir -p /var/www/html
      - cp *.html *.php /var/www/html/
  post_build:
    commands:
      - echo Configuring HTTPD...
      - sudo service httpd restart
      - sudo systemctl enable httpd
  artifacts: null
  files:
    - "**/*"
  discard-paths: no


