version: 0.2

phases:
  install:
    commands:
      - echo Installing Apache HTTPD
      - sudo yum update -y
      - sudo yum install -y httpd  # installing httpd server
  pre_build:
    commands:
      - echo Starting HTTPD server...
      - sudo nohup systemctl restart httpd &
      - echo HTTPD started successfully

  build:
    commands:
      - echo Build starting on 'date'
      - sudo mkdir -p /var/www/html
      - cp *.html /var/www/html/
      - echo Build completed and files copied

  post_build:
    commands:
      - echo Configuring HTTPD...
      - sudo service httpd status  # Confirm the server is running post-restart

artifacts: {}  # Explicitly defining artifacts as an empty map

files:
  - "**/*"

discard-paths: no
