version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
      docker: 18
    commands:
      # Install Nginx
      - echo "Installing Nginx"
      - sudo amazon-linux-extras enable nginx1
      - sudo yum install -y nginx
      - sudo systemctl start nginx
      - sudo systemctl enable nginx
      - sudo yum install -y git

  pre_build:
    commands:
      # Download or prepare your website files (you can use Git or an S3 bucket)
      - echo "Setting up website"
      - echo "Hello, World! This is my AWS CodeBuild website!" > /tmp/index.html

  build:
    commands:
      # Move the HTML to the Nginx web directory
      - echo "Deploying website to Nginx"
      - sudo mv /tmp/index.html /usr/share/nginx/html/index.html

  post_build:
    commands:
      # Restart Nginx to apply changes
      - echo "Restarting Nginx"
      - sudo systemctl restart nginx

artifacts:
  files:
    - /usr/share/nginx/html/index.html
